export const SPECIALTIES: string[] = [
  "Allergy & Immunology",
  "Anesthesiology",
  "Bariatric Surgery",
  "Cardiology",
  "Cardiothoracic Surgery",
  "Colorectal Surgery",
  "Dermatology",
  "Endocrinology",
  "Family Medicine",
  "Gastroenterology",
  "General Surgery",
  "Genetics",
  "Geriatrics",
  "Gynecologic Oncology",
  "Gynecology",
  "Hematology",
  "Hematology-Oncology",
  "Hepatology",
  "Infectious Disease",
  "Internal Medicine",
  "Maternal-Fetal Medicine",
  "Nephrology",
  "Neurology",
  "Neurosurgery",
  "Obstetrics",
  "Oncology (Medical)",
  "Ophthalmology",
  "Orthopedic Surgery",
  "Otolaryngology (ENT)",
  "Pain Management",
  "Palliative Care",
  "Pediatrics",
  "Physical Medicine & Rehabilitation",
  "Plastic Surgery",
  "Podiatry",
  "Psychiatry",
  "Pulmonology",
  "Radiation Oncology",
  "Rheumatology",
  "Sleep Medicine",
  "Sports Medicine",
  "Urgent Care",
  "Urology",
  "Vascular Surgery",
  "Wound Care",
];

export const OTHER_SPECIALTY = "Other";
